travel/apps/orders/urls.py
# _*_ encoding:utf-8 _*_

from django.conf.urls import url,include

from .views import *


urlpatterns = [
    url('^team/$', TeamOrderView.as_view(), name='team'),
    url('^add/$', AddOrderView.as_view(), name='add_order'),
    url('^order/$', AddOrderView.as_view(), name='order'),
    url('^pay/$', OrderPayView.as_view(), name='pay'),
    url('^order_new/$', OrderNewView.as_view(), name='order_new'),
    url('^order_his/$', OrderHisView.as_view(), name='order_his'),
    url('^my_info/$', MyInfoView.as_view(), name='my_info'),
    url('^update_info/$', UpdateInfoView.as_view(), name='update_info'),
    url('^update_mobile/$', UpdateMobileView.as_view(), name='update_mobile'),
    url('^update_email/$', UpdateEmailView.as_view(), name='update_email'),
    url(r'^captcha/', include('captcha.urls')),
    url('^update_man/$', UpdateManView.as_view(), name='update_man'),
    url('^delete_man/$', DeleteManView.as_view(), name='delete_man'),
    url('^reset_pwd/$', ResetPwdView.as_view(), name='reset_pwd'),
]

travel/travel/urls.py
# _*_ encoding:utf-8 _*_
"""travel URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
import xadmin
from django.views.static import serve
from .settings import MEDIA_ROOT

from users.views import *
from route.views import *
from route.views_long import *
from orders import views as orderview


urlpatterns = [
    url(r'^$',IndexView_Redict.as_view()),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^index/$', IndexView.as_view(), name="index"),
    # 账号登录与注册
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    # 加载验证码
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="useractive"),
    url(r'^forget$', ForgetView.as_view(), name="forget"),
    url(r'^retrievepwd/(?P<active_code>.*)/$', RetrievePwdView.as_view(), name="retrievepwd"),
    url(r'^reset_pwd/$', ResetpwdView.as_view(), name="resetpwd"),
    # 列表展示
    url(r'^identical_list/$', IdenticalListView.as_view(), name="identical_list"),
    url(r'^long_list/$', LongListView.as_view(), name="long_list"),
    url(r'^short_list/$', ShortListView.as_view(), name="short_list"),
    url(r'^list_details/(?P<id>[0-9]+)$', ListDetailsView.as_view(), name="list_details"),
    # 处理静态文件的函数
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    # url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),
    # 订单提交
    url(r'^order/', include('orders.urls', namespace='order')),

    # 底部
    url(r'^common_problem/$', CommonProblemView.as_view(), name="common_problem"),
    url(r'^contact_us/$', ContactUsView.as_view(), name="contact_us"),
    url(r'^join_us/$', JoinUs.as_view(), name="join_us"),
    url(r'^disclaimer/$', DisclaimerView.as_view(), name="disclaimer"),
    url(r'^base/$', BaseView.as_view(), name='base'),

    url(r'^celery/',orderview.celery,name='celery'),
    url(r'^log/',orderview.log_test,name='log'),

    url(r'^error/',ErrorView.as_view(),name='error'),
]

#配置全局404页面
handler404 = 'users.views.page_not_found'
#配置全局500页面
handler500 = 'users.views.page_error'

travel/extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

travel/templates/Contact_Us.html
{% extends 'details.html' %}
{% load staticfiles %}
{% block title %}<title>联系我们/悠悠蜗</title>{% endblock %}
{% block crumbs %}
    <div id="Title"><div class="w-1180">悠悠蜗-联系我们</div></div>
    <!-- /Title -->
{% endblock %}
{% block content %}
    <div id="Contene" class="bg-fafafa UsWra">
        <div class="Us w-1180">
            <h2>联系悠悠蜗</h2>
            <p>我们期待每一个和您交流的机会，无论是投诉还是祝福，意见或建议，知道悠悠蜗最近做了什么，还是想加入我们的团队，这里就是开始。无论您在世界的任何一个角落对我们提出意见或建议，我们保证您都将得到我们的回复。</p>
            <p>我们热忱欢迎每个人来电，我们也珍惜每一个和您交流的机会，无论是祝福，还是意见或者建议，或者是其他想要了解的问题，我们都会耐心解决。</p>
            <ul class="TXt">
                <li><strong>悠悠蜗电话：</strong><span>021-80000000</span></li>
                <li><strong>悠悠蜗EmaiL：</strong><span>admin@yooyoowo.com</span></li>
                <li><strong>悠悠蜗地址：</strong><span>上海市杨浦区国定东路200号1号楼1113室 </span></li>
            </ul>
            <div class="Map"><img src="{% static 'images/map2.jpg' %}" alt="地图"></div>
        </div>
    </div>
    <!-- /Contene --> 
{% endblock %}

travel/templates/ModifyPwd.html
{% extends 'details.html' %}
{% load staticfiles %}
{% block title %}
    <title>修改密码/悠悠蜗</title>
{% endblock %}
{% block content %}
    <div id="Contene">
	<div class="Order">
		<div class="TopWra">
			<div class="Top w-1180 clearFix">
				<div class="f-l">我的订单</div>
				<div class="f-r">
					<a href="{% url 'order:order_new' %}" class="btn tr-02">当前订单</a>
					<a href="{% url 'order:order_his' %}" class="btn tr-02">历史订单</a>
					<a href="{% url 'order:my_info' %}" class="btn tr-02 active">我的信息</a>
				</div>
			</div>
		</div>
		<div class="Bottom  w-1180">
			<div class="Modify text-center">
				<form class="form" action="{% url 'order:reset_pwd' %}" method="post">
                    {% csrf_token %}
					<ul class="text-right">
						<li>
							<strong>用户邮箱：</strong>
							<span><input class="txt-input1 tr-02 focus-input" type="text" name="email" autofocus="autofocus" /></span>
						</li>
						<li>
							<strong>邮箱验证码：</strong>
							<span>
								<input class="txt-input2 pull-left tr-02 focus-input" name="captcha" type="tel"/>
								<button type="button" class="btn btn1 send_email">发送邮件</button>
							</span>
						</li>
                        <li>
							<strong>新密码：</strong>
							<span><input class="txt-input1 tr-02 focus-input" type="text" name="password1" autofocus="autofocus" /></span>
						</li>
                        <li>
							<strong>确认密码：</strong>
							<span><input class="txt-input1 tr-02 focus-input" type="text" name="password2" autofocus="autofocus" /></span>
						</li>
						<li>
							<span>
								<button type="submit" class="btn btn2 w-100">提 交</button>
							</span>
						</li>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>
    <!-- /Contene -->
{% endblock %}
{% block custom_js %}
<script>
    $('.send_email').click(function () {
        console.log('点击');
        $.ajax({
            type: "POST",
            url:"{% url 'order:reset_pwd' %}",
            data:$('.form').serialize(),
            success:function (data) {
                if(data['status'] == 'success'){
                    $('.send_email').text('验证码已发送')
                }else if(data['status'] == 'fail'){
                    alert('请输入正确的邮箱')
                }else if(data['status'] == 'none'){
                    alert('用户邮箱错误')
                }
            },
        });
    })
</script>
{% endblock %}

travel/templates/Order_My_C_ModifyMan.html
{% extends 'details.html' %}
{% block title %}
    <title>填写信息/悠悠蜗</title>
{% endblock %}
{% block content %}
    <div id="Contene">
	<div class="Order">
		<div class="TopWra">
			<div class="Top w-1180 clearFix">
				<div class="f-l">我的订单</div>
				<div class="f-r">
					<a href="{% url 'order:order_new' %}" class="btn tr-02">当前订单</a>
					<a href="{% url 'order:order_his' %}" class="btn tr-02">历史订单</a>
					<a href="{% url 'order:my_info' %}" class="btn tr-02 active">我的信息</a>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="Contene" class="w-1180" style="margin-top:-500px">
	<div class="Short-List-SignUp">
		<div class="SignUpDiv clearFix">
              <div class="f-l">
                    <section>
                        <div class="section clearFix">
                            <h4>出行人信息</h4>
                            {% for man in user_man %}
                            <div class="Information">
                                <div class="Top clearFix">
                                    <span class="f-l">{{ man.name }}</span>
                                    <div class="f-r">
                                        <a class="tr-02 edit" href="" data-toggle="modal" data-target="#edit">编辑</a>
                                        <a class="tr-02 delete" href="">删除</a>
                                    </div>
                                </div>
                                <div class="Txt">
                                    <ul class="clearFix">
                                        <li class="f-l">真实姓名：<span>{{ man.name }}</span></li>
                                        {% if man.gender == '0' %}
                                        <li class="f-l">性别：<span>男</span></li>
                                        {% else %}
                                        <li class="f-l">性别：<span>女</span></li>
                                        {% endif %}
                                        <li class="f-l">手机号：<span>{{ man.mobile }}</span></li>
                                        <li class="f-l">邮箱：<span>{{ man.email }}</span></li>
                                        {% if man.card_type == '0' %}
                                        <li class="f-l">证件类型：<span>身份证</span></li>
                                        {% else %}
                                        <li class="f-l">证件类型：<span>护照</span></li>
                                        {% endif %}
                                        <li class="f-l">证件号：<span>{{ man.card }} </span></li>
                                        <li class="f-l" style="display: none"><span>{{ man.id }} </span></li>
                                    </ul>
                                </div>
                            </div>
                            {% endfor %}
                            <button class="btn f-r addman" data-toggle="modal" data-target="#edit">添加出行人</button>
                        </div>
                    </section>
                    <form class="info_delete">
                        {% csrf_token %}
                        <input type="text" class="id" hidden name="man_id" value="">
                    </form>
                    <!-- 添加出行人弹窗 -->
                    <div role="dialog" class="modal fade" id="edit">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                   <button type="button" class="close" data-dismiss="modal">
                                    <span>&times;</span>
                                   </button>
                                   <h4>填写出行人信息<span>（<i>*</i>为必填选项）</span></h4>
                                </div>
                                <div class="modal-body text-right">
                                    <form class="info">
                                        {% csrf_token %}
                                        <ul>
                                            <li>
                                                <strong><i>*</i>姓&nbsp;&nbsp;&nbsp;名：</strong>
                                                <span><input class="input-txt focus-input" type="text" name="name" autofocus="autofocus" value=""></span>
                                            </li>
                                            <li>
                                                <strong><i>*</i>姓&nbsp;&nbsp;&nbsp;别：</strong>
                                                <span class="text-left">
                                                       <label>
                                                              <input class="click" type="radio" value="0" name="gender"/>
                                                              <span>男</span>
                                                       </label>
                                                       <label>
                                                              <input class="click" type="radio" value="1" name="gender"/>
                                                              <span>女</span>
                                                       </label>
                                                 </span>
                                            </li>
                                            <li>
                                                <strong><i>*</i>手机号：</strong>
                                                <span><input class="input-txt focus-input" type="text" name="mobile" value=""></span>
                                            </li>
                                            <li>
                                                <strong><i>*</i>邮&nbsp;&nbsp;&nbsp;箱：</strong>
                                                <span><input class="input-txt focus-input" type="text" name="email" value=""></span>
                                            </li>
                                            <li>
                                                <strong><i>*</i>
                                                    <select class="select" name="card_type">
                                                    <option value="0">身份证</option>
                                                    <option value="1">护照</option>
                                                </select>
                                            </strong>
                                                <span><input class="input-txt focus-input" name="card" type="text" value=""></span>
                                            </li>
                                            <li style="display: none"><input name="man_id" value="" hidden></li>
                                            <li>
                                                 <span class="text-left"><button type="button" class="btn add_userman " data-dismiss="modal" value="1">提交</button></span>
                                            </li>
                                            <input type="checkbox" name="status" value="1" checked="checked" hidden>
                                        </ul>
                                    </form>
                                </div>
                            </div>
                        </div>
                 </div>
                  <!-- / 添加出行人弹窗 -->
              </div>
        </div>
    </div>
</div>
<!-- /Contene -->
{% endblock %}
{% block custom_js %}
    <script>
    $(".add_userman").click(function () {
        //用于判断添加还是修改
        var type = $('.add_userman').val()
        console.log(type)
        if(type == '1'){
            $.ajax({
            type: "POST",
            url: "{% url 'order:add_order' %}",
            data: $(".info").serialize(),
            success: function(data) {
                    if(data["status"]== 'success'){
                        $("div.section").children('div:last').after('<div class="Information" style="display:block"><div class="Top clearFix"><span class="f-l"></span><div class="f-r"><a class="tr-02 button_edit" href="JavaScript:;" data-toggle="modal" data-target="#edit">编辑</a><a class="tr-02 button_del" href="JavaScript:;">删除</a></div></div><div class="Txt"><ul class="clearFix"><li class="f-l">真实姓名：<span>李大根</span></li><li class="f-l">性别：<span>女</span></li><li class="f-l">证件类型：<span>身份证</span></li><li class="f-l">证件号：<span>362523199204170818 </span></li><!-- <li class="f-l">护照号码：<span>23213265</span></li> --><li class="f-l">手机号：<span>13302580258</span></li><li class="f-l">邮箱：<span>18507317473@163.com</span></li><!-- <li class="f-l">保险：<span>赠送  平安保险--神州畅游 A款 </span></li> --></ul></div></div>')
                        var man = data["info"]
                        var name= $("div.Information:last").children('.Top').find('span').text(man['name'])
                        var u_name= $("div.Information:last").children('.Txt').find('span').eq(0).text(man['name'])
                        var gender= $("div.Information:last").children('.Txt').find('span').eq(1).text(man['gender'])
                        var card_type= $("div.Information:last").children('.Txt').find('span').eq(2).text(man['card_type'])
                        var card= $("div.Information:last").children('.Txt').find('span').eq(3).text(man['card'])
                        var mobile= $("div.Information:last").children('.Txt').find('span').eq(4).text(man['mobile'])
                        var email= $("div.Information:last").children('.Txt').find('span').eq(5).text(man['email'])
                    }else if(data["status"] == 'fail'){
                        console.log(data["status"],data["info"])
                        alert("出行人添加失败")
                    }
                },
            }
        );
        }
        else{
            $.ajax({
                type: "POST",
                url: "{% url 'order:update_man' %}",
                data: $(".info").serialize(),

            });
        }
    });
    $('.edit').click(function(){
    var value = $('.add_userman').val('0')
    console.log(value.val())
	var father = $(this).parents('.Information')
	var children = father.find('ul li')
	var name = children.eq(0).find('span').text()
	var gender = children.eq(1).find('span').text()
	var mobile = children.eq(2).find('span').text()
	var email = children.eq(3).find('span').text()
	var card_type = children.eq(4).find('span').text()
	var card = children.eq(5).find('span').text()
	var man_id = children.eq(6).find('span').text()
	console.log(name,gender,mobile,email,card_type,card)
	var info = $('.modal').find('form ul li')
	var info_name = info.eq(0).find('input').val(name)
	var info_mobile = info.eq(2).find('input').val(mobile)
	var info_email = info.eq(3).find('input').val(email)
	var info_card = info.eq(4).find('input').val(card)
	var info_id = info.eq(5).find('input').val(man_id)
        console.log(info_id.val())
	var info_gender = info.eq(1).find('input');
	if(gender == '男'){
		info_gender.eq(1).removeAttr('checked');
		info_gender.eq(0).attr('checked','checked')
	}else if(gender == '女'){
		info_gender.eq(0).removeAttr('checked');
		info_gender.eq(1).attr('checked','checked')
	};
});
    $('.addman').click(function(){
    var value = $('.add_userman').val('1')
    console.log(value.val())
	var info = $('.modal').find('form ul li')
	var info_name = info.eq(0).find('input').val('')
	var info_mobile = info.eq(2).find('input').val('')
	var info_email = info.eq(3).find('input').val('')
	var info_card = info.eq(4).find('input').val('')

});
    $('.delete').click(function(){
        var father = $(this).parents('.Information')
        var children = father.find('ul li')
        var man_id = children.eq(6).find('span').text()
        $('.info_delete').find('input.id').val(man_id)
        $.ajax({
                type: "POST",
                url: "{% url 'order:delete_man' %}",
                data: $(".info_delete").serialize(),

        });
    });
</script>
{% endblock %}

travel/templates/Order_My_C_ModifyMobile.html
{% extends 'details.html' %}
{% block title %}
    <title>手机号修改/悠悠蜗</title>
{% endblock %}
{% block content %}
<div id="Contene">
	<div class="Order">
		<div class="TopWra">
			<div class="Top w-1180 clearFix">
				<div class="f-l">我的订单</div>
				<div class="f-r">
					<a href="{% url 'order:order_new' %}" class="btn tr-02">当前订单</a>
					<a href="{% url 'order:order_his' %}" class="btn tr-02">历史订单</a>
					<a href="{% url 'order:my_info' %}" class="btn tr-02 active">我的信息</a>
				</div>
			</div>
		</div>
		<div class="Bottom  w-1180">
			<div class="Modify text-center">
				<form class="form">
					<ul class="text-right">
						<li>
							<strong>手机号码：</strong>
							<span><input class="txt-input1 tr-02 focus-input" type="tel" autofocus="autofocus" /></span>
						</li>
						<li>
							<strong>短信验证码：</strong>
							<span>
								<input class="txt-input2 pull-left tr-02 focus-input" type="tel"/>
								<button type="button" class="btn btn1">获取动态验证码</button>
							</span>
						</li>
						<li>
							<span>
								<button type="button" class="btn btn2 w-100">验证手机</button>
							</span>
						</li>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- /Contene -->
{% endblock %}